# Generated by Django 5.2.6 on 2025-09-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='айди источника')),
                ('source_name', models.CharField(max_length=255, verbose_name='название источника')),
                ('author', models.CharField(max_length=255, verbose_name='автор статьи')),
                ('title', models.CharField(max_length=255, verbose_name='название статьи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание статьи')),
                ('url', models.URLField(unique=True, verbose_name='ссылка на статью')),
                ('url_to_image', models.URLField(blank=True, null=True, verbose_name='ссылка на картинку')),
                ('published_at', models.DateTimeField(verbose_name='дата публикации')),
                ('content', models.TextField(blank=True, null=True, verbose_name='текст статьи')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'ordering': ('-published_at',),
            },
        ),
    ]
